Repository StoKatze/Unofficial-Infra-Game-Italian-Translation, pull requests merged in 2021-05, with the labels that each got.

#1 Improvements to Walter's tape and minor fixes
  subtitles_italian.txt
Labels: bug

#2 C1_M1 Revision
  Subtitles/closecaption_italian.txt
  Subtitles/subtitles_italian.txt
Labels: enhancement

#3 C2_M1 Revision
  Subtitles/subtitles_italian.txt
Labels: bug, enhancement
